version: "3.8"

services:
  devcontainer:
    command: sleep infinity
    env_file: .env
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    networks:
      - network
    volumes:
      - ..:/workspaces/backend:cached

  database:
    env_file: .env
    image: postgres:latest
    networks:
      - network
    ports:
      - 5432:5432

networks:
  network:
    driver: bridge
