name: Publish SDK

on:
  push:
    branches: main

permissions:
  contents: read
  id-token: write

jobs:
  deploy-api:
    environment: deployment
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein/packages.lock.json
      - run: dotnet restore Mortein/
      - run: dotnet tool restore

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm clean-install

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazon.com
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions

      - run: |
          dotnet lambda deploy-serverless \
          --s3-bucket mortein-api \
          --stack-name MorteinApiStack
        working-directory: Mortein/
