name: Status Checks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm clean-install

  prettier:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm clean-install
      - run: npx prettier --check .

  dotnet:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein*/packages.lock.json

      - run: dotnet restore
      - run: dotnet tool restore

  dotnet-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein*/packages.lock.json
      - run: dotnet restore
      - run: dotnet tool restore

      - run: dotnet build -warnaserror

  dotnet-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein*/packages.lock.json
      - run: dotnet restore
      - run: dotnet tool restore

      - run: dotnet format --verify-no-changes

  dotnet-test:
    environment: testing
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file from `testing` Environment
        run: |
          echo '${{ toJson(secrets) }}' \
            | jq -r 'to_entries[] | "\(.key)=\(.value)"' > .devcontainer/.env
          echo '${{ toJson(vars) }}' \
            | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> .devcontainer/.env
          echo 'GITHUB_ACTIONS=true' >> .devcontainer/.env

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazon.com
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions

      - name: .NET Tests
        uses: devcontainers/ci@v0.3.1900000349
        with:
          runCmd: dotnet test
