name: Status Checks

on:
  pull_request:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm clean-install

  prettier:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm clean-install
      - run: npx prettier --check .

  dotnet:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein/packages.lock.json

      - run: dotnet restore Mortein/
      - run: dotnet tool restore

  dotnet-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein/packages.lock.json

      - run: dotnet restore Mortein/
      - run: dotnet tool restore

      - run: dotnet build Mortein/ -warnaserror

  dotnet-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
          cache: true
          cache-dependency-path: Mortein/packages.lock.json

      - run: dotnet restore Mortein/
      - run: dotnet tool restore

      - run: dotnet format Mortein/ --verify-no-changes

  terraform-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

      - run: terraform fmt -check

  terraform-validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

      - run: terraform validate
